window.FREELY_CATALOG = {
  "schemaVersion": 1,
  "lastUpdated": "2026-07-18T06:24:21.949Z",
  "sources": [
    {
      "id": "muse-asia",
      "name": "Muse Asia",
      "ok": true,
      "fetchedAt": "2026-07-18T06:24:21.949Z",
      "feedItems": 15,
      "eligibleItems": 7
    },
    {
      "id": "kofa",
      "name": "Korean Film Archive",
      "ok": true,
      "fetchedAt": "2026-07-18T06:24:21.949Z",
      "feedItems": 15,
      "eligibleItems": 1
    },
    {
      "id": "jff",
      "name": "JFF Theater",
      "ok": true,
      "fetchedAt": "2026-07-18T06:24:21.949Z",
      "feedItems": 17,
      "eligibleItems": 17
    }
  ],
  "summary": {
    "total": 37,
    "available": 35,
    "unavailable": 2,
    "autoDiscovered": 19
  },
  "items": [
    {
      "id": "1",
      "title": "Hyouka",
      "year": "2012",
      "type": "Series",
      "focus": "Animation",
      "genre": "Mystery",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "School mystery",
      "art": "linear-gradient(145deg,#293c38,#d99e95)",
      "image": "https://i.ytimg.com/vi/lTAAB0xn3yY/hq720.jpg",
      "words": "HYOUKA",
      "url": "https://www.youtube.com/watch?v=lTAAB0xn3yY",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:1",
      "accessEvidence": "curated-hardsub",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null
    },
    {
      "id": "2",
      "title": "Cautious Hero",
      "year": "2019",
      "type": "Series",
      "focus": "Animation",
      "genre": "Fantasy",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Fantasy comedy",
      "art": "linear-gradient(145deg,#13284a,#8a59ba)",
      "image": "https://i.ytimg.com/vi/XRBQS_x_1n0/hq720.jpg",
      "words": "CAUTIOUS\nHERO",
      "url": "https://www.youtube.com/watch?v=XRBQS_x_1n0",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:2",
      "accessEvidence": "curated-hardsub",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null
    },
    {
      "id": "3",
      "title": "Gakuen Babysitters",
      "year": "2018",
      "type": "Series",
      "focus": "Animation",
      "genre": "Slice of Life",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Warm & gentle",
      "art": "linear-gradient(145deg,#8bbdc3,#f3b99a)",
      "image": "https://i.ytimg.com/vi/qxSlgYAec2E/hq720.jpg",
      "words": "GAKUEN\nBABYSITTERS",
      "url": "https://www.youtube.com/watch?v=qxSlgYAec2E",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:3",
      "accessEvidence": "curated-hardsub",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null
    },
    {
      "id": "4",
      "title": "A Certain Magical Index",
      "year": "2008",
      "type": "Series",
      "focus": "Animation",
      "genre": "Fantasy",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Science fantasy",
      "art": "linear-gradient(145deg,#19436a,#db6e67)",
      "image": "https://i.ytimg.com/vi/pQY088rA1iA/hq720.jpg",
      "words": "MAGICAL\nINDEX",
      "url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl01_ftoIT3birJWkpxFZkEl",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:4",
      "accessEvidence": "curated-hardsub",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T00:00:00.000Z",
      "checkError": null
    },
    {
      "id": "5",
      "title": "Arte",
      "year": "2020",
      "type": "Series",
      "focus": "Animation",
      "genre": "Drama",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Historical drama",
      "art": "linear-gradient(145deg,#251b32,#cc6a63)",
      "image": "https://i.ytimg.com/vi/B1nDigzGDAg/hq720.jpg",
      "words": "ARTE",
      "url": "https://www.youtube.com/watch?v=B1nDigzGDAg",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:5",
      "accessEvidence": "official-title",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null
    },
    {
      "id": "6",
      "title": "Grimoire of Zero",
      "year": "2017",
      "type": "Series",
      "focus": "Animation",
      "genre": "Adventure",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Fantasy adventure",
      "art": "linear-gradient(145deg,#176b8d,#efc23c)",
      "image": "https://i.ytimg.com/vi/uGYM9uX5qDI/hq720.jpg",
      "words": "GRIMOIRE\nOF ZERO",
      "url": "https://www.youtube.com/watch?v=uGYM9uX5qDI",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "muse-asia",
      "sourceKey": "curated:6",
      "accessEvidence": "official-title",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null
    },
    {
      "id": "7",
      "title": "A Coachman",
      "year": "1961",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Drama",
      "platform": "Korean Film Archive",
      "runtime": 99,
      "tag": "Korean classic",
      "art": "linear-gradient(145deg,#40332a,#b07856)",
      "image": "https://i.ytimg.com/vi/7gykTo0eEgc/hq720.jpg",
      "words": "A\nCOACHMAN",
      "url": "https://www.youtube.com/watch?v=7gykTo0eEgc",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:7",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:34:12.579Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": null
    },
    {
      "id": "8",
      "title": "Under the Sky of Seoul",
      "year": "1961",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Drama",
      "platform": "Korean Film Archive",
      "runtime": 126,
      "tag": "Restored classic",
      "art": "linear-gradient(145deg,#3a171b,#9d5148)",
      "image": "https://i.ytimg.com/vi/XxMG1IhCLZY/hq720.jpg",
      "words": "UNDER THE SKY\nOF SEOUL",
      "url": "https://www.youtube.com/watch?v=XxMG1IhCLZY",
      "access": "EN SUB",
      "availability": "unavailable",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:8",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T00:00:00.000Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": "english-sub-or-dub-not-found"
    },
    {
      "id": "9",
      "title": "A Sunflower Family",
      "year": "1961",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Drama",
      "platform": "Korean Film Archive",
      "runtime": 122,
      "tag": "Family drama",
      "art": "linear-gradient(145deg,#24313c,#9a8768)",
      "image": "https://i.ytimg.com/vi/61Ug8pRHcqQ/hq720.jpg",
      "words": "A SUNFLOWER\nFAMILY",
      "url": "https://www.youtube.com/watch?v=61Ug8pRHcqQ",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:9",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:34:12.579Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": null
    },
    {
      "id": "10",
      "title": "A Bloodthirsty Killer",
      "year": "1965",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Horror",
      "platform": "Korean Film Archive",
      "runtime": 93,
      "tag": "Gothic horror",
      "art": "linear-gradient(145deg,#100f12,#6c1f28)",
      "image": "https://i.ytimg.com/vi/rVVtAPh2M9Q/hq720.jpg",
      "words": "BLOODTHIRSTY\nKILLER",
      "url": "https://www.youtube.com/watch?v=rVVtAPh2M9Q",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:10",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:34:12.579Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": null
    },
    {
      "id": "11",
      "title": "The Devil's Stairway",
      "year": "1964",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Thriller",
      "platform": "Korean Film Archive",
      "runtime": 108,
      "tag": "Psychological thriller",
      "art": "linear-gradient(145deg,#273a57,#cd7a87)",
      "image": "https://i.ytimg.com/vi/VnvRpQFsgrY/hq720.jpg",
      "words": "DEVIL'S\nSTAIRWAY",
      "url": "https://www.youtube.com/watch?v=VnvRpQFsgrY",
      "access": "EN SUB",
      "availability": "unavailable",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:11",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T00:00:00.000Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": "english-sub-or-dub-not-found"
    },
    {
      "id": "12",
      "title": "A Female Boss",
      "year": "1959",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Comedy",
      "platform": "Korean Film Archive",
      "runtime": 105,
      "tag": "Classic comedy",
      "art": "linear-gradient(145deg,#34506b,#dc8a79)",
      "image": "https://i.ytimg.com/vi/T5vT42pCwfI/hq720.jpg",
      "words": "A FEMALE\nBOSS",
      "url": "https://www.youtube.com/watch?v=T5vT42pCwfI",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "kofa",
      "sourceKey": "curated:12",
      "accessEvidence": "english-caption-track",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:34:12.579Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": null
    },
    {
      "id": "13",
      "title": "The Miracles of Namiya General Store",
      "year": "2017",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Fantasy",
      "platform": "JFF Theater",
      "runtime": 129,
      "tag": "Time-crossing drama",
      "art": "linear-gradient(145deg,#1d2550,#d4955a)",
      "image": "https://www.jff.jpf.go.jp/images/2026/03/withcredit_namiya19.jpg",
      "words": "NAMIYA\nGENERAL STORE",
      "url": "https://www.jff.jpf.go.jp/movie/namiya-general-store/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:13",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "14",
      "title": "The Blue Sky You Dropped",
      "year": "2022",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Romance",
      "platform": "JFF Theater",
      "runtime": 93,
      "tag": "Youth romance",
      "art": "linear-gradient(145deg,#267aa1,#e1a6b3)",
      "image": "https://www.jff.jpf.go.jp/images/2026/06/withcredit_The_-Blue_Skies_at_Your_Feet_main.jpg",
      "words": "THE BLUE\nSKY",
      "url": "https://www.jff.jpf.go.jp/movie/the-blue-skies-at-your-feet/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:14",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "15",
      "title": "The 100th Love with You",
      "year": "2017",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Romance",
      "platform": "JFF Theater",
      "runtime": 116,
      "tag": "Time-loop romance",
      "art": "linear-gradient(145deg,#365879,#e4aaae)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/withcredit_The-100th-Love-with-You_Main.jpg",
      "words": "100TH LOVE\nWITH YOU",
      "url": "https://www.jff.jpf.go.jp/movie/100-love-with-you/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:15",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "16",
      "title": "Erased",
      "year": "2016",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Thriller",
      "platform": "JFF Theater",
      "runtime": 120,
      "tag": "Mystery thriller",
      "art": "linear-gradient(145deg,#132b3b,#7a8793)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/withcredit_Erased_main.jpg",
      "words": "ERASED",
      "url": "https://www.jff.jpf.go.jp/movie/erased/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:16",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "17",
      "title": "Yudo",
      "year": "2023",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Comedy",
      "platform": "JFF Theater",
      "runtime": 126,
      "tag": "Bathhouse comedy",
      "art": "linear-gradient(145deg,#293b35,#ca9d65)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/with-creditYUDO_main.jpg",
      "words": "YUDO",
      "url": "https://www.jff.jpf.go.jp/movie/yudo/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:17",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "18",
      "title": "Tora-san, Our Lovable Tramp",
      "year": "1969",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Comedy",
      "platform": "JFF Theater",
      "runtime": 91,
      "tag": "Beloved classic",
      "art": "linear-gradient(145deg,#5d3928,#dbb976)",
      "image": "https://www.jff.jpf.go.jp/images/2026/05/withcredit_Tora-San_Main.jpg",
      "words": "TORA-SAN",
      "url": "https://www.jff.jpf.go.jp/movie/tora-san-our-lovable-tramp/",
      "access": "EN SUB",
      "availability": "available",
      "curated": true,
      "sourceId": "jff",
      "sourceKey": "curated:18",
      "accessEvidence": "official-page",
      "discoveredAt": "2026-07-18T00:00:00.000Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "unavailableReason": null,
      "checkError": null
    },
    {
      "id": "jff:sagrada-reset-part1",
      "title": "Sagrada Reset — Part 1",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#3d253f,#7d79bd)",
      "image": "https://www.jff.jpf.go.jp/images/2026/03/withcredit_SAGRADA_RESET_Part1_main01.jpg",
      "words": "SAGRADA RESET —\nPART 1",
      "url": "https://www.jff.jpf.go.jp/movie/sagrada-reset-part1/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:sagrada-reset-part1",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:sagrada-reset-part2",
      "title": "Sagrada Reset — Part 2",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#172b3a,#c45b58)",
      "image": "https://www.jff.jpf.go.jp/images/2026/03/withcredit_SAGRADA_RESET_Part2_main01.jpg",
      "words": "SAGRADA RESET —\nPART 2",
      "url": "https://www.jff.jpf.go.jp/movie/sagrada-reset-part2/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:sagrada-reset-part2",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:sumo-do-sumo-dont",
      "title": "Sumo Do Sumo Dont",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#172b3a,#c45b58)",
      "image": "https://www.jff.jpf.go.jp/images/2026/05/withcredit_SDSD_main.jpg",
      "words": "SUMO DO\nSUMO DONT",
      "url": "https://www.jff.jpf.go.jp/movie/sumo-do-sumo-dont/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:sumo-do-sumo-dont",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:shodo-girls",
      "title": "Shodo Girls",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#29223f,#c77c55)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/withcredit_SHODO_GIRLS_main.jpg",
      "words": "SHODO GIRLS",
      "url": "https://www.jff.jpf.go.jp/movie/shodo-girls/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:shodo-girls",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:every-day-a-good-day",
      "title": "Every Day A Good Day",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#29223f,#c77c55)",
      "image": "https://www.jff.jpf.go.jp/images/2025/12/withcredit_Every_Day_a_Good_Day_main01.jpg",
      "words": "EVERY DAY A\nGOOD DAY",
      "url": "https://www.jff.jpf.go.jp/movie/every-day-a-good-day/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:every-day-a-good-day",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:bonsai-warrior",
      "title": "Bonsai Warrior",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#29223f,#c77c55)",
      "image": "https://www.jff.jpf.go.jp/images/2026/02/withcredit_bonsaisub_main-69858590058e7.jpg",
      "words": "BONSAI WARRIOR",
      "url": "https://www.jff.jpf.go.jp/movie/bonsai-warrior/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:bonsai-warrior",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:inuyashiki",
      "title": "Inuyashiki",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#3d253f,#7d79bd)",
      "image": "https://www.jff.jpf.go.jp/images/2026/06/withcredit_INUYASHIKI_still_main.jpg",
      "words": "INUYASHIKI",
      "url": "https://www.jff.jpf.go.jp/movie/inuyashiki/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:inuyashiki",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:discovering-with-new-eyes",
      "title": "Discovering With New Eyes",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#3b3022,#5d92a7)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/withcredit_Traditional_Performing_Arts02.jpg",
      "words": "DISCOVERING WITH\nNEW EYES",
      "url": "https://www.jff.jpf.go.jp/movie/discovering-with-new-eyes/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:discovering-with-new-eyes",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:5-sword-accoutrements",
      "title": "5 Sword Accoutrements",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#172b3a,#c45b58)",
      "image": "https://www.jff.jpf.go.jp/images/2026/04/withcredit_Sword_Accoutrements04.jpg",
      "words": "5 SWORD\nACCOUTREMENTS",
      "url": "https://www.jff.jpf.go.jp/movie/5-sword-accoutrements/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:5-sword-accoutrements",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:ki-ki-shamisen",
      "title": "Ki Ki Shamisen",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#3b3022,#5d92a7)",
      "image": "https://www.jff.jpf.go.jp/images/2025/04/withcredit_03KiKi：-Blending-Old-and-New-Sounds-with-Shamisen.png",
      "words": "KI KI\nSHAMISEN",
      "url": "https://www.jff.jpf.go.jp/movie/ki-ki-shamisen/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:ki-ki-shamisen",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "jff:japanese-yokai-01",
      "title": "Japanese Yokai 01",
      "year": "Current",
      "type": "Movie",
      "focus": "Japanese",
      "genre": "Japanese cinema",
      "platform": "JFF Theater",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#172b3a,#c45b58)",
      "image": "https://www.jff.jpf.go.jp/images/2025/07/withcredit_japanese_yokai003.jpg",
      "words": "JAPANESE YOKAI\n01",
      "url": "https://www.jff.jpf.go.jp/movie/japanese-yokai-01/",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "jff",
      "sourceKey": "jff:japanese-yokai-01",
      "publishedAt": null,
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-page"
    },
    {
      "id": "muse-asia:rilakkuma",
      "title": "Rilakkuma",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#183957,#a7648a)",
      "image": "https://i2.ytimg.com/vi/9KfHgDhxXhE/hqdefault.jpg",
      "words": "RILAKKUMA",
      "url": "https://www.youtube.com/watch?v=9KfHgDhxXhE",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:rilakkuma",
      "publishedAt": "2026-07-18T01:00:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:draw-this-then-die",
      "title": "Draw This, Then Die!",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#253d32,#d18d58)",
      "image": "https://i2.ytimg.com/vi/1AO0RStBvbI/hqdefault.jpg",
      "words": "DRAW THIS,\nTHEN DIE!",
      "url": "https://www.youtube.com/watch?v=1AO0RStBvbI",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:draw-this-then-die",
      "publishedAt": "2026-07-17T16:00:07+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:that-time-i-got-reincarnated-as-a-slime",
      "title": "That Time I Got Reincarnated as a Slime",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#3b3022,#5d92a7)",
      "image": "https://i3.ytimg.com/vi/Bk7B8RqSzSk/hqdefault.jpg",
      "words": "THAT TIME I\nGOT REINCARNATED",
      "url": "https://www.youtube.com/watch?v=Bk7B8RqSzSk",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:that-time-i-got-reincarnated-as-a-slime",
      "publishedAt": "2026-07-17T15:00:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:fullmetal-alchemist-brotherhood",
      "title": "Fullmetal Alchemist: BROTHERHOOD",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#253d32,#d18d58)",
      "image": "https://i3.ytimg.com/vi/BQObyzlORgA/hqdefault.jpg",
      "words": "FULLMETAL ALCHEMIST:\nBROTHERHOOD",
      "url": "https://www.youtube.com/watch?v=BQObyzlORgA",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:fullmetal-alchemist-brotherhood",
      "publishedAt": "2026-07-17T13:00:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:the-exiled-heavy-knight-knows-how-to-game-the-system",
      "title": "The Exiled Heavy Knight Knows How to Game the System",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#253d32,#d18d58)",
      "image": "https://i4.ytimg.com/vi/_k_d8xiuIZA/hqdefault.jpg",
      "words": "THE EXILED HEAVY\nKNIGHT KNOWS",
      "url": "https://www.youtube.com/watch?v=_k_d8xiuIZA",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:the-exiled-heavy-knight-knows-how-to-game-the-system",
      "publishedAt": "2026-07-16T17:56:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:kaiju-girl-caramelise",
      "title": "KAIJU GIRL CARAMELISE",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#172b3a,#c45b58)",
      "image": "https://i2.ytimg.com/vi/1qoetg03sJE/hqdefault.jpg",
      "words": "KAIJU GIRL\nCARAMELISE",
      "url": "https://www.youtube.com/watch?v=1qoetg03sJE",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:kaiju-girl-caramelise",
      "publishedAt": "2026-07-16T17:28:07+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "muse-asia:bang-dream-yume-mita",
      "title": "BanG Dream! YUME∞MITA",
      "year": "2026",
      "type": "Series",
      "focus": "Animation",
      "genre": "Animation",
      "platform": "Muse Asia",
      "runtime": 24,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#183957,#a7648a)",
      "image": "https://i4.ytimg.com/vi/c-i7twaxhq4/hqdefault.jpg",
      "words": "BANG DREAM!\nYUME∞MITA",
      "url": "https://www.youtube.com/watch?v=c-i7twaxhq4",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "muse-asia",
      "sourceKey": "muse-asia:bang-dream-yume-mita",
      "publishedAt": "2026-07-16T14:00:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:24:21.949Z",
      "checkError": null,
      "unavailableReason": null,
      "accessEvidence": "official-title"
    },
    {
      "id": "kofa:sisters-garden",
      "title": "Sisters' Garden",
      "year": "2026",
      "type": "Movie",
      "focus": "Korean",
      "genre": "Classics",
      "platform": "Korean Film Archive",
      "runtime": 110,
      "tag": "Auto-discovered",
      "art": "linear-gradient(145deg,#183957,#a7648a)",
      "image": "https://i2.ytimg.com/vi/AxraJIX5PQI/hqdefault.jpg",
      "words": "SISTERS' GARDEN",
      "url": "https://www.youtube.com/watch?v=AxraJIX5PQI",
      "access": "EN SUB",
      "availability": "available",
      "curated": false,
      "autoDiscovered": true,
      "sourceId": "kofa",
      "sourceKey": "kofa:sisters-garden",
      "publishedAt": "2026-07-13T13:00:06+00:00",
      "discoveredAt": "2026-07-18T06:27:06.230Z",
      "lastCheckedAt": "2026-07-18T06:24:21.949Z",
      "accessVerifiedAt": "2026-07-18T06:34:12.579Z",
      "checkError": "caption-metadata-unavailable",
      "unavailableReason": null,
      "accessEvidence": "english-caption-track"
    }
  ]
};
